version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: playing-cards-service
    image: 'playingcardsservice'
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html